Set Pos1 when breaking a block.
SIsilicon/WorldEdit-BE pull request #111
Opened 2022-08-29 09:42 UTC by Fynn93

When you break a block, pos1 will automatically be set on the broken Block's coordinates. (The Block will get placed again)

Shift + Right Click is still supported.

#99 can be closed.

2022-08-29 20:51 UTC, SIsilicon commented on src/server/tools/selection_tools.ts
> +    if (brokenBlockPermutation.type.id == 'minecraft:air') return
In case other items will use `breakOn`, move the logic for reverting the break to `ToolManager.onBlockBreak`.

2022-08-29 20:53 UTC, SIsilicon commented on src/server/tools/selection_tools.ts
> +    let comp = player.getComponent("inventory") as EntityInventoryComponent
This part of the code is redundant since detecting if a tool is being used is already done in `ToolManager.onBlockBreak`. Also, please don't restrict it to `WAND_ITEM`.

2022-08-29 20:54 UTC, SIsilicon requested changes
Due to how block break works, it will have undesirable effects on blocks with custom data (chests, command blocks, etc...). If you can make the use of block break optional in the config file, that would be great.

2022-08-30 11:00 UTC, Fynn93 commented
Done (see commit #[882921c](https://github.com/SIsilicon/WorldEdit-BE/pull/111/commits/882921c23b79153827687ee61e1ec44fedab8f71))

2022-08-31 21:27 UTC, SIsilicon commented
The build's failing without eslint guiding the code format. You'll need to download eslint from the node package manager and use it for code formatting.

2022-09-04 07:24 UTC, Fynn93 commented
Fixed (see commit [#8ef5440](https://github.com/SIsilicon/WorldEdit-BE/pull/111/commits/8ef5440036004851566ad5e223d19fb00a13026b)

2022-09-17 21:18 UTC, SIsilicon commented
Thanks!

2022-09-17 21:18 UTC, merged