Add Ascend and Descend
SIsilicon/WorldEdit-BE pull request #112
Opened 2022-08-29 15:07 UTC by Fynn93

Added Ascend and Descend
(Not the Best Implementation but it works!)

2022-08-29 20:41 UTC, SIsilicon commented on src/server/commands/navigation/ascend.ts
> +const registerInformation = {
The ascend command has a `levels` parameter that determines how many "floors" to go through.
https://worldedit.enginehub.org/en/latest/usage/navigation/?highlight=ascend#ascending-and-descending

2022-08-29 20:42 UTC, SIsilicon commented on src/server/commands/navigation/descend.ts
> +    name: "descend",
The descend command has a `levels` parameter that determines how many "floors" to go through.
https://worldedit.enginehub.org/en/latest/usage/navigation/?highlight=ascend#ascending-and-descending

2022-08-29 20:43 UTC, SIsilicon commented on texts/en_US.po
> +msgid "commands.wedit:ascend.explain"
To optimize the number of language keys used, You can replace `commands.wedit:ascend/descend.explain` with `commands.wedit:thru.explain`.

2022-08-29 20:45 UTC, SIsilicon requested changes
If you can add the `levels` parameter to these two commands that would be great.

2022-08-30 10:35 UTC, Fynn93 commented
Done (see commit #9088179)

2022-08-31 21:31 UTC, SIsilicon commented
There seems to be some indentation, trailing spaces and semicolons missing. These are the errors from eslint.
```
/home/runner/work/WorldEdit-BE/WorldEdit-BE/src/library/Minecraft.ts
  194:1  error  Trailing spaces not allowed  no-trailing-spaces

/home/runner/work/WorldEdit-BE/WorldEdit-BE/src/server/commands/navigation/ascend.ts
   7:1   error  Expected indentation of 2 spaces but found 4         indent
   8:1   error  Expected indentation of 2 spaces but found 4         indent
   9:1   error  Expected indentation of 2 spaces but found 4         indent
  [10](https://github.com/SIsilicon/WorldEdit-BE/runs/8123310493?check_suite_focus=true#step:8:11):1   error  Expected indentation of 2 spaces but found 4         indent
  [11](https://github.com/SIsilicon/WorldEdit-BE/runs/8123310493?check_suite_focus=true#step:8:12):1   error  Expected indentation of 4 spaces but found 8         indent
  [12](https://github.com/SIsilicon/WorldEdit-BE/runs/8123310493?check_suite_focus=true#step:8:13):1   error  Expected indentation of 6 spaces but found 12        indent
  [13](https://github.com/SIsilicon/WorldEdit-BE/runs/8123310493?check_suite_focus=true#step:8:14):1   error  Expected indentation of 6 spaces but found 12        indent
  [14](https://github.com/SIsilicon/WorldEdit-BE/runs/8123310493?check_suite_focus=true#step:8:15):1   error  Expected indentation of 6 spaces but found 12        indent
  [15](https://github.com/SIsilicon/WorldEdit-BE/runs/8123310493?check_suite_focus=true#step:8:16):1   error  Expected indentation of 4 spaces but found 8         indent
  [16](https://github.com/SIsilicon/WorldEdit-BE/runs/8123310493?check_suite_focus=true#step:8:17):1   error  Expected indentation of 2 spaces but found 4         indent
  [20](https://github.com/SIsilicon/WorldEdit-BE/runs/8123310493?check_suite_focus=true#step:8:21):1   error  Expected indentation of 2 spaces but found 4         indent
  20:9   error  'location' is never reassigned. Use 'const' instead  prefer-const
  [21](https://github.com/SIsilicon/WorldEdit-BE/runs/8123310493?check_suite_focus=true#step:8:22):1   error  Expected indentation of 2 spaces but found 4         indent
  [23](https://github.com/SIsilicon/WorldEdit-BE/runs/8123310493?check_suite_focus=true#step:8:24):1   error  Expected indentation of 2 spaces but found 4         indent
  [24](https://github.com/SIsilicon/WorldEdit-BE/runs/8123310493?check_suite_focus=true#step:8:25):1   error  Expected indentation of 4 spaces but found 8         indent
  24:13  error  'floor' is never reassigned. Use 'const' instead     prefer-const
  [25](https://github.com/SIsilicon/WorldEdit-BE/runs/8123310493?check_suite_focus=true#step:8:26):1   error  Expected indentation of 4 spaces but found 8         indent
  25:13  error  'legs' is never reassigned. Use 'const' instead      prefer-const
  [26](https://github.com/SIsilicon/WorldEdit-BE/runs/8123310493?check_suite_focus=true#step:8:27):1   error  Expected indentation of 4 spaces but found 8         indent
  26:13  error  'head' is never reassigned. Use 'const' instead      prefer-const
  [28](https://github.com/SIsilicon/WorldEdit-BE/runs/8123310493?check_suite_focus=true#step:8:29):1   error  Expected indentation of 4 spaces but found 8         indent
  28:28  error  Missing semicolon                                    semi
  [30](https://github.com/SIsilicon/WorldEdit-BE/runs/8123310493?check_suite_focus=true#step:8:31):1   error  Expected indentation of 4 spaces but found 8         indent
  30:62  error  Missing semicolon                                    semi
  [31](https://github.com/SIsilicon/WorldEdit-BE/runs/8123310493?check_suite_focus=true#step:8:32):1   error  Expected indentation of 4 spaces but found 8         indent
  31:62  error  Missing semicolon                                    semi
  [32](https://github.com/SIsilicon/WorldEdit-BE/runs/8123310493?check_suite_focus=true#step:8:33):1   error  Expected indentation of 4 spaces but found 8         indent
  32:62  error  Missing semicolon                                    semi
  [34](https://github.com/SIsilicon/WorldEdit-BE/runs/8123310493?check_suite_focus=true#step:8:35):1   error  Expected indentation of 4 spaces but found 8         indent
  [36](https://github.com/SIsilicon/WorldEdit-BE/runs/8123310493?check_suite_focus=true#step:8:37):1   error  Expected indentation of 6 spaces but found 12        indent
  [37](https://github.com/SIsilicon/WorldEdit-BE/runs/8123310493?check_suite_focus=true#step:8:38):1   error  Expected indentation of 6 spaces but found 12        indent
  [38](https://github.com/SIsilicon/WorldEdit-BE/runs/8123310493?check_suite_focus=true#step:8:39):1   error  Expected indentation of 4 spaces but found 8         indent
  [39](https://github.com/SIsilicon/WorldEdit-BE/runs/8123310493?check_suite_focus=true#step:8:40):1   error  Expected indentation of 2 spaces but found 4         indent
  [40](https://github.com/SIsilicon/WorldEdit-BE/runs/8123310493?check_suite_focus=true#step:8:41):1   error  Expected indentation of 2 spaces but found 4         indent
  40:65  error  Missing semicolon                                    semi
  [44](https://github.com/SIsilicon/WorldEdit-BE/runs/8123310493?check_suite_focus=true#step:8:45):1   error  Expected indentation of 2 spaces but found 4         indent
  44:9   error  'levels' is never reassigned. Use 'const' instead    prefer-const
  [46](https://github.com/SIsilicon/WorldEdit-BE/runs/8123310493?check_suite_focus=true#step:8:47):1   error  Expected indentation of 2 spaces but found 4         indent
  [47](https://github.com/SIsilicon/WorldEdit-BE/runs/8123310493?check_suite_focus=true#step:8:48):1   error  Expected indentation of 4 spaces but found 8         indent
  [48](https://github.com/SIsilicon/WorldEdit-BE/runs/8123310493?check_suite_focus=true#step:8:49):1   error  Expected indentation of 2 spaces but found 4         indent
  [50](https://github.com/SIsilicon/WorldEdit-BE/runs/8123310493?check_suite_focus=true#step:8:51):1   error  Expected indentation of 2 spaces but found 4         indent

/home/runner/work/WorldEdit-BE/WorldEdit-BE/src/server/commands/navigation/descend.ts
   7:1   error  Expected indentation of 2 spaces but found 4         indent
   8:1   error  Expected indentation of 2 spaces but found 4         indent
   9:1   error  Expected indentation of 2 spaces but found 4         indent
  10:1   error  Expected indentation of 2 spaces but found 4         indent
  11:1   error  Expected indentation of 4 spaces but found 8         indent
  12:1   error  Expected indentation of 6 spaces but found 12        indent
  13:1   error  Expected indentation of 6 spaces but found 12        indent
  14:1   error  Expected indentation of 6 spaces but found 12        indent
  15:1   error  Expected indentation of 4 spaces but found 8         indent
  16:1   error  Expected indentation of 2 spaces but found 4         indent
  20:1   error  Expected indentation of 2 spaces but found 4         indent
  20:9   error  'location' is never reassigned. Use 'const' instead  prefer-const
  21:1   error  Expected indentation of 2 spaces but found 4         indent
  23:1   error  Expected indentation of 2 spaces but found 4         indent
  24:1   error  Expected indentation of 4 spaces but found 8         indent
  24:13  error  'floor' is never reassigned. Use 'const' instead     prefer-const
  25:1   error  Expected indentation of 4 spaces but found 8         indent
  25:13  error  'legs' is never reassigned. Use 'const' instead      prefer-const
  26:1   error  Expected indentation of 4 spaces but found 8         indent
  26:13  error  'head' is never reassigned. Use 'const' instead      prefer-const
  28:1   error  Expected indentation of 4 spaces but found 8         indent
  28:28  error  Missing semicolon                                    semi
  30:1   error  Expected indentation of 4 spaces but found 8         indent
  30:[62](https://github.com/SIsilicon/Wor [...]

2022-09-04 07:23 UTC, Fynn93 commented
Fixed (see commit [#dd36a62](https://github.com/SIsilicon/WorldEdit-BE/pull/112/commits/dd36a62ef04e8936a749bae760caa9d95fc36b87))

2022-09-17 21:18 UTC, SIsilicon commented
Thanks!

2022-09-17 21:18 UTC, merged