Add super pickaxe
SIsilicon/WorldEdit-BE pull request #215
Opened 2023-10-30 20:51 UTC by CrackedMatter

2023-11-01 09:26 UTC, CrackedMatter commented
Not sure if this should support undo/redo, what do you think?

2023-11-07 20:28 UTC, SIsilicon commented
> Not sure if this should support undo/redo, what do you think?

I think it's fine to not support undo/redo. I'll just check out these changes now

2023-11-07 21:24 UTC, SIsilicon requested changes

2023-11-07 21:24 UTC, SIsilicon commented on src/config.ts
Configuration needs to be registered in worldedit_settings.json

2023-11-07 21:24 UTC, SIsilicon commented on src/server/sessions.ts
Maybe we should make it so the super pickaxe is saved with the player. Not a necessity but consider it

2023-11-07 21:24 UTC, SIsilicon commented on src/server/tools/superpickaxe_tool.ts
In Java edition the `area` mode only affects blocks of the same type as the one the player broke.
Also, we should make it so that we instead run logic on block break instead of on hit. That way we can break consecutive blocks by just holding the attack button.

2023-11-09 15:57 UTC, CrackedMatter commented on src/config.ts
Done

2023-11-09 16:08 UTC, CrackedMatter commented on src/server/sessions.ts
I wouldn't make it persistent because it can be very destructive and users might forget they enabled it.

2023-11-13 12:55 UTC, merged